### ISSUE TITLE
Extensions behavior is not defined

### ISSUE THREAD

**Issue by empijei** [w3c/webappsec-fetch-metadata#12]
Browser extensions currently have a different threat model than normal web pages: they can inject arbitrary scripts into pages and ask the user for access to many other browser features.

I am wondering which Sec-Fetch header values should browser send when an action is initiated by an extension, or a resource is framed or added to a page by an extension's script.

* `Dest`: this is probably going to stay unchanged
* `Mode`: does it make sense to have an "extension" mode? Some developers might want to be able to allow extensions to use some resources, but not anything else (after all extensions act as components of the user agent). If not, should maybe "same-site" be sent instead?
* `Site`: this is probably the toughest one: extensions would technically be considered "cross-origin" (or at least the current chrome implementation does) but does this really give a meaningful signal? In the event of servers denying "cross-origin" operation it would just make it harder to develop non-malicious extensions without granting any additional protection against malicious ones.
* `User`: if a user asks an extension (e.g. via click) to perform some actions in a page, are those actions to be considered user initiated?

CC: @arturjanc

**Comment by arturjanc** [comment]
Something we may want to clarify is whether we're considering this to affect the behavior only of background scripts or also of contents scripts; I'd expect that since content scripts execute in the context of a given web page they would behave in the same way as the script on the page?

For background scripts, my guess is that `dest`, `mode` and `user` could also behave the same way as elsewhere (e.g. an API that fetches resources in `cors` mode from a background script would send `Sec-Fetch-Mode: cors`). For `Site`, one possible solution would be to create a new value that applies to loads which cannot be initiated by regular web content. For example, navigations initiated from a bookmark, by typing a URL directly into the address bar, and possibly resource/document loads from an extension could all set `Sec-Fetch-Site: external` or something similar. 

The main benefit here is reducing the likelihood that locking down websites against cross-origin requests will break extensions which request permissions to a given origin, but whose requests would otherwise still be identified as cross-origin.

**Comment by anforowicz** [comment]
Please also note that in other places we have been trying to make extension content scripts behave exactly as a webpage would.  In particular:
- https://crbug.com/846346#c27 stops making a CORB exception for content scripts and https://crbug.com/920638 tracks the work to stop making a CORS exception
- https://crbug.com/920638#c9 argues that Origin header (and I would argue all headers based on [request_initiator](https://cs.chromium.org/search/?q=network::ResourceRequest::request_initiator&sq=package:chromium&type=cs), including `Sec-Fetch-Site`) should specify the webpage's origin, rather than extension origin

cc @csreis

**Comment by mikewest** [comment]
Would one of you be interested in proposing some explanatory text for the spec about recommendations for extensions, etc?
