### ISSUE TITLE
Sec-Fetch-Site's use of "initiator" is misleading

### ISSUE THREAD

**Issue by domenic** [w3c/webappsec-fetch-metadata#72]
> The Sec-Fetch-Site HTTP request header exposes the relationship between a request initiator’s origin and its target’s origin.

Here "initiator" is very unclear. According to the normative algorithm, it appears to mean "first URL in the redirect chain, or the target URL if there are no redirects".

However, when colloquially talking about navigations, "initiator" often means "the code that started the navigation". E.g. if `https://outer.example/` iframes `https://inner.example/` and did `frames[0].location.href = "https://dest.example/"` then I would expect the "initiator" to be `https://outer.example/`. Whereas from what I can tell of the algorithm, `Sec-Fetch-Site` will instead be `https://dest.example/`.

**Comment by mikewest** [comment]
I think the spec intends to use "initiator" in the way you describe. It sets the header using a comparison against the request's origin (step 5.1 of https://w3c.github.io/webappsec-fetch-metadata/#abstract-opdef-set-site), just as other fetch-related origin comparisons do.

There may be a mistake in the algorithm that I'm missing due to looking at it too often, so I'm happy to make changes or add clarification if that would be helpful.

**Comment by domenic** [comment]
Hmm, yep, sorry for wasting time---I seem to have somehow missed the reference to the request's origin, or not understood that that origin was derived from the initiator. Thanks for the quick response!
